name: Migrations

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install
        env:
          CI: true
      - name: Run Storybook
        run: npm run storybook -- --ci --smoke-test --quiet
